### ISSUE TITLE
Dancer Bug

### ISSUE THREAD

**Issue by Spineshatter** [Asureon/UI_Collections#1]
When using En Avant the Middle frame glitches to 1/4 of a frame after using the last charge of En Avant. I'm really loving this setup! thank you!
![Dancer](https://github.com/Asureon/UI_Collections/assets/167583265/82290fc9-bb76-4908-8e5a-d923c41bf056)

Also on the layout for dancer you provided for your lvl 62, all of your icons are showing even the ones greyed out.  Mine are not and i am lvl 69.
![Dancer2](https://github.com/Asureon/UI_Collections/assets/167583265/c67b5b75-1c4f-413c-9e59-bd00e235d259)

**Comment by Asureon** [comment]
I'm, still levelling dancer and I still currently have only 1 charge on En Avant, but I'll take a look into it

**Comment by Asureon** [comment]
The icons not showing is intentional to show if you're a high enough level or not to use it. I've only set everything to show for the preview picture. If an icon is greyed out, it means you're at a high enough level, but there's a condition which won't allow you to cast it. (For example Fan dance at 0 feathers)

**Comment by Spineshatter** [comment]
Standard step is level 15, and does not show on my bar. You do have it on your example.

Thank you for all of your hard work and effort. I hope this feedback helps.  Thank You

**Comment by Asureon** [comment]
DelvCD has been updated. Rewired the Skills background so that it isn't in the DNC group anymore and I've rerolled Standard Step to a previous version.

**Comment by Asureon** [comment]
Also noticed that Devilment and Fan Dance III aren't showing either

**Comment by Spineshatter** [comment]
I tried copying. AST essential dignity parameters to the En Avant but it all looked the same to me. I didn't see anything different. The 2 spell/abilities have 2 charges and CD at a certain lvl. Only difference I saw was essential dignity is on the primary bar and my AST is lvl 90.  
I have to go till tomorrow, I have work in the AM.
Thanks Again!

**Comment by Spineshatter** [comment]
Don't know if this helps narrow where the issue might be but, I just did 2 duty roulettes and standard step only shows when in a raid/duty and dungeon/duty. Not solo or in a party.

Also in primary field / combos you have starfall dance listed twice.  I believe the first 1 listed should be tillana since you have the lvl set to 82 and the last starfall dance should be correct since it is listed as lvl 90.

Didnt know if having 2 of the same name might cause a bug but just thought i would mention it.

**Comment by Asureon** [comment]
That's rather odd. Could you check the visibility settings of the Cooldowns group and see if there's anything checked? Nothing should be. Also check the visibility settings of the elements within it like Standard Step aswell. The way you describe it, the most logical reason would be that "Hide Outside Duty" is checked on your part. (No idea how though)

![image](https://github.com/Asureon/UI_Collections/assets/167483871/55737587-1f8f-468e-9264-3e9c00827221)

You're correct on the Tillana part though, but that shouldn't be causing the issue. It's just a name change overall. Anyways, fixing that right now.

**Comment by Asureon** [comment]
> Also in primary field / combos you have starfall dance listed twice. I believe the first 1 listed should be tillana since you have the lvl set to 82 and the last starfall dance should be correct since it is listed as lvl 90.

Fixed.

**Comment by Spineshatter** [comment]
I have fixed the En Avant issue by exporting the Ast essential dignity and re naming it En Avant . But I cannot figure out how to move it back. I mean i can move it but i cant re size it and move it. it stays under the sprint icon.

here is the code for En Avant
7Brbcho39Fc8mj5umV3AYHgjEDu0NDDBcdIyjLssMqheVoykBdNOvqwP/aT+Qo8ue+NmJzGGpPvACJ1zpHN0dG6S9t+///kL/SBWc4zqqIX9RbNVeN9+7eMZDgQvtD0aIAtdK7xtIdnvi5WPmzS4IxNU3xisEYV1Qgv1KCeCwHSpMf0VF3hWeBvOMCMeL9xgT1BWtM4MosfIwhUYJmW4Q0Ywy0dULzsFkORXkKdgf7JQn/yJv3rOUtXMKf/ISad0+YqyMWaoLliILaR711Pi3QeYc1R3IliT+pTt1oRuNJGFtDSPy1veL2+kAtX+ZtoPqv1kxO8xOmEgaX9JJB+9igjYcoXbpyHzcDsY4we1t5u4S4L9cULQDhaYiRvXDzGs/871eWpGxaY7dz0iVnJrKhG94W/IpWQK0iHBllkk9AT1mRYvZQJFC1154+wCI0A38FcxsIW5K0IGbJVDReBYXYqdRHXn2kWg2wy5oDNNX6zZZYAwOs+Mv/LpMtNZkw0gfTxRnozqFwYwx3hsOMr+MbRtF2q2U6vYF8aNzy8uiqXzktK8ndV8LGLxxWWMg0xGLlvLJffhmIa6LpZSF8jVcUfY7xAuHgvQa4TWmUYDF4UBgxnsSwyKKM4MsHUK8KTUsEEJs+AHcUnZzBVAPfAo9cd0GdwKAqoZPmfuSO2qdGuXwWIagTeVO2NrORo+mWgPvKSBaLdQvaL//ozBU9GM4DEJJpj9OAIpb52KEf8Eo5aMtd1Q+BC0ovhvusdx+l0Oda6DgRT5HQ0DqV6l/7fuTHKT2kVyOcZkxsoU+G7x1wh/dwaD/RYYGf9wmHIDwz3FECJwivvgaey/kPs1IxMwsm15WvfV3+5cNSolG42qib/c+Y7ubE4t7W19Mpv7uEUY8AORGozRJb8t2t+I00V5/vS8zki7z98y3SEAbggnI+JDxfJYiN+gtFDDX7or/oaME7XITjvoLXoZCCiLQ7MObkO6nY2kjW7S7sa0QllepeAfpsTHPczuwODVujMsriCk46Dvhp4s/DPDADzFrpjK4skg2pMAVL0hWATO8G76ZJ5ldtfBC0ihW2DSq4sZiHHwmq3tC7z1JzqSqZenSkUA9QVTi5JuHANlkodwNYx3NNmd1DZrFtLuGFfOj8BECvADmqMXAly43j1/1kqguCc4VTPBqZoEp/N9lUDxGwlKeSXwvVUCzndZCeTOlhcAeQHwYgVAX+XY7RVAXv0dqvrTyfgpxd/5IfbeJJfHKrUsWTxM31buy4BNU8GZAclQI83r4KyxcAOhMqrUY/zS0Bj/AWtINGgm2gBIfZWSbjoBNqcum0B2C2H+eFgCi0YmkMxgEIemuEEvQlvoPXdHMrcarO4m6HculIXNKfbuYxIFSig6lGfxAEiwccmgs6NSiZM5+KeKgm3af4P9OXhxIU0WW0BK5215E1yxHXP7DPooV6Dc/cV9MNFAslVrl5TSijK7tOVk8Fmcq9VKOeJcvShnGJcOyLhYK5fiJdfK0rNSnMt7ODsyFL6gsevwcEBbd07I1sHWcls/LVsfPuu969qj8Msetp7C/AlnLcjN0pmczzpr5a/hx779yF/D89fw/DX8//YabpKJSn6767ZDZg7nK2/p8sxxzOexPHOc9ndU5ikj/4wq/4zqgIlDHoI2D1dbrkn/AwAA//8DAA==

**Comment by Spineshatter** [comment]
Also I figured out that either something in the primary is wrong with fan dance 3 and 4 because when i was testing the en avant i moved fan dance 3 and 4 to the bottom of the list and all of the icons showed up where they were suposed to be.



Hope this helps

![dancer3](https://github.com/Asureon/UI_Collections/assets/167583265/29b30abf-3276-4d5d-8140-f1e5d16552dd)

**Comment by Asureon** [comment]
Try this by putting it in the Tertiary field

7BrbcuI29Fd2NH10Pba5JPBGYZOlpRtmyWbbZpjUGAXUGIuRZAjt7Jf1oZ/UX+jRxTcgJLsbCLv1AyN0zpHO0dG5SfK/f//zF/pOrOYYNVEHh4t2x37ffR3iGY4Et7sBjZCFLhXesZDsD8QqxG0a3ZIJam4M1gh7ndBCfcqJIDBdbsxgxQWe2W/jGWYk4PYVDgRlnvXKIPqMLHyBYVKGe2QEs/yCmjUbBPkVNSu289FCA/In/uIpvUYyp6MnndLlD5SNMUNNwWJsId27nJLgLsKco6abwNo0pOxhRehGE1lIS/O4vNXd8rpGXNX+ZtoPqv1oxO8zOmEg6WBJJB+9igTY8YU/oDELcDca43u1tZu4M4LDcUbQjRaYiSs/jDGs/9YPeW5GxeZi7gdErIDarif0hr8hl5IpSI9EW2aR0CPUZ168nAl4FjoPxsUFJoCLKFylwA7mvogZsFX+lIBTdSl2EnUx1x4C3XbMBZ1peq/hVAHC6Lww/jyky0JnTTaADPBEOTJqnhrAHOOx4Sj7L6Ftx244bqPunCqdO3bt9NSr1CpK805R86mI3sFl1Bah2pxcjpZL7sNLGuq6WEpdIFfPH+GwR7h4LD6vEVqvNBq4KAwYzPWuvKCI0sQAW6cAT8oMG5QwC74XZ5TNfAHU1wGl4ZguoxtBQDXD50wduV2Vbu0zWEwrCqZyZxwtRyskE+2BZzQS3Q5q1vXfnzB4KpoRPCbRBLPvRyDljVs34h9h1JKx9iIWIQStJP6b7ss4/UMOVdPBQIr8jsaRVK/S/1t/JrlJ7SK5HGMyY2UK/GHx1wh/d6+vd1tgYvzDYc4NDPccQ4jAOe7XT2P/mdwvGZmAkW3L07qv/l7MVaNSstGomvjzne/Fnc1t5L1tQGbzEHcIA34gUosxuuQ3nvOVOF2S54/P64y0u/yt0B0C4IpwMiIhVCyPhfgNSgu1wqW/4m/IOFOL7HSj/qJfgICyODTr4C6k29lI2ugm7cOYTizLqxz8w5SEuI/ZLRi8WneBxTmEdBwN/DiQhX9hGICn2BdTWTwZRHcSgao3BEvABd7tkMyLzG57eAEpdAtMerVXgBgHbzjavsBbf6QjmXp5rlQE0EAwtSjpxilQJnkIV8N0R7PdyW2zZiHtjnHl/AhMxIYf0Lx4IcCFH9zxZ60EvB3B6aQQnE6y4FTbVQl4X0lQKiuBb60ScL/JSqB0trIAKAuAgxUAA5Vjt1cAZfW3r+pPJ+OnFH+1fey9SS6PVWpFsnSYvq3clQHbpoIzA7KhRprX0avWwo+EyqhSj+lDQ2v8B6wh06CZaAMg9VXJuvkE2J76bALZLYb502EZLBmZQQqDQRya4wa9BG2h99wfydxqsLqbod/5UBa2pzi4S0kUKKPoUV7EAyDDpiWDzo5KJW7h4J8rCrZp/w0O5+DFdp4stYCczrvyJrjuuOb2GfRRrUO5+7N/b6KBZKvWLimlFRV2acvJ4JM4n5zUqwnnk9NqgXFlj4y9RrWSLrlRlZ6V41zdwdmVofCAxq7Dwx5t3T0iWwdbK239uGx9+Kz3rmtvwoc9bD2F+RPOWpCbpTO5n3TWKh/Dy8fw8jG8fAwvH8MP+hhuconKfQ+XbftMHO4XXtIdIHE4/9+vqB55HCu/ojrur6jMQ0b5EVX5EdUe84Y8Am0erbZckv4HAAD//wMA

**Comment by Asureon** [comment]
> Also I figured out that either something in the primary is wrong with fan dance 3 and 4 because when i was testing the en avant i moved fan dance 3 and 4 to the bottom of the list and all of the icons showed up where they were suposed to be.

I wish I could give an explanation to this but I'm clueless on how that caused the issue, other than the fact that the lowest element in the list has the highest strata. Yet there shouldn't be anything masking it. Anyways, glad you resolved it!
Does it happen again when you put Fan Dance 3 and 4 back to its original place?

**Comment by Spineshatter** [comment]
> > Also I figured out that either something in the primary is wrong with fan dance 3 and 4 because when i was testing the en avant i moved fan dance 3 and 4 to the bottom of the list and all of the icons showed up where they were suposed to be.
> 
> I wish I could give an explanation to this but I'm clueless on how that caused the issue, other than the fact that the lowest element in the list has the highest strata. Yet there shouldn't be anything masking it. Anyways, glad you resolved it! Does it happen again when you put Fan Dance 3 and 4 back to its original place?

The code for the Tertiary field worked perfectly.  Thank You

As for the primary I was waiting your opinion on my En Avant fix, to make sure I was helping and not hurting. Plus There was the 
"Also in primary field / combos you have starfall dance listed twice. I believe the first 1 listed should be tillana since you have the lvl set to 82 and the last starfall dance should be correct since it is listed as lvl 90."

to all come togther b4 I did more tinkering.  It's your baby I am just trying to help, because you have an awesome thing here.

**Comment by Asureon** [comment]
Ofcourse, any feedback is always appreciated.
Also got a new version of your En Avant, less triggers/conditions for things to mess up lol.
But yeah, check on the Fan Dance 3/4 if you want and let me know.

7Flbcxo3FP4rHk0ftzvLcueNQuzQ0sAEx2nLMO6yyKB6WTGSFkw6+WV9yE/KX+jRZW+AwU1t4yQ8eGSdc6Tv6OjcWH3+59Pf6AexXmDUQG0cLFtt+13nVYDnOBTc7vg0RBa6VHzHQnI+EOsAt2h4Q6aosbVYM+xNQQv1KSeCwHaZNYM1F3huv4nmmBGf21fYF5S51plh9BlZegLDpgx3yRh2+Q01yjYo8jtqFG3no4UG5AP+31u69XhPR286o6ufKJtghhqCRdhCenY5I/5tiDlHjUJMa9GAsvsNoQctZCGtzWF9S/v1LRh11fiHGd+r8aNRv8/olIGmgxWROPoUMbHtCW9AI+bjTjjBd+pqt3nnBAeTVKATLjETV14QYTj/jRfwzI4KprfwfCLWIG1XYnmDb8SlZorSJeGOXST1Bdozq17GBVwLXfiT/AFjQi8M1gmxjbknIgawKp5icmIuBSdZvYWOEJi2Ii7oXMu7dacEFEYXufUXAV3lJhu6AWWApyqQUaNmCAuMJwZRzo9hbceuO4V6xakpmzt2uVZzi+WisryTt3yiovvsOmqPUGNGL0frJe/hmI66qZYyF+jV9cY46BIuDuXnDUHrTLMBRXHAYYb76oISSgoDXJ0iPKgybEnCLvhOnFM29wRID31KgwldhdeCgGlGj1k6Mrcqw9pjcJhm6M/kzThaj2ZApjoCz2koOm0IpZr+/xcMoYrmBE9IOMXsxzGoeV2oGP1fYNqSybYXiQCyVlwAzPQ4UX9fRJV1NpAqv6VRKM2rLuCNN5do0rpIHsf4zET5Ar9f/Q3BPwvD4X4XjL1/NMrEgUHPAEIKzqAPHwb/heiXjEzByXYVaj1X//YWalA12VhUbfzl0Xf0aCvUs9E2IPNFgNuEAR6o1GSMrvi163wlQRcX+pcXdUbbffGWm46AcEU4GZMAWpZDOX5L0kLNYOWt+WsySc0iJ52wv+znKGAsDsMmuQP1dj6WProtez+nHcn+KkN/PyMB7mN2Aw6vzp2DuICUjsOBF/my888tA/IMe2ImuyfD6ExDMPWWYjE5h90KyCIPdtPFS6ihO2gyqt0cxQR43dH+BdH6Mx3L2sszvSKQBoKpQ8kwToiyykO6GiU3mt5O5po1hPQ7xlXwI3ARG/5A5uidABeef8sftRVw9ySnai45VdPkVHT3tQLuV5KVTq3At9YKFL7JVqB8CrZTB/AddAA6Hz+kAajUnq4BGKgau7sDOHV/x7/78lM0f6a2HOrU8mLJMv25cl8BbJkOzixIlxptXoVnzaUXClVQpR2Tl4bm5C84Q2pBs9EWQdqrmE6z9a8189gUUkME+yfLUlq8MqXkFoM6NIMGs5htoXfcG8vSarh6mrLfetAVtmbYv01EFCmV6FKe5wMh5SYdgy6OyiSF3A//TE+wy/qvcbCAKLazYokHZGzekZ+CK07BfH4Ge5Qq0O7+6t2ZbCBh1dmlpPSi3C3t+GXwn5Cr1UopRq7WSjng4hMCu/VSMTlyvSQjK4Nc2oNcgFQ4etRvURsPZc/bfz4E/Knaz2d4IXS+3xfCA999Ti+EL/uF0PxEPz0Qnh4IH/eB0JQS5WWqkm1XyB39/78AAAD//wMA

**Comment by Spineshatter** [comment]
> Ofcourse, any feedback is always appreciated. Also got a new version of your En Avant, less triggers/conditions for things to mess up lol. But yeah, check on the Fan Dance 3/4 if you want and let me know.
> 
> 7Flbcxo3FP4rHk0ftzvLcueNQuzQ0sAEx2nLMO6yyKB6WTGSFkw6+WV9yE/KX+jRZW+AwU1t4yQ8eGSdc6Tv6OjcWH3+59Pf6AexXmDUQG0cLFtt+13nVYDnOBTc7vg0RBa6VHzHQnI+EOsAt2h4Q6aosbVYM+xNQQv1KSeCwHaZNYM1F3huv4nmmBGf21fYF5S51plh9BlZegLDpgx3yRh2+Q01yjYo8jtqFG3no4UG5AP+31u69XhPR286o6ufKJtghhqCRdhCenY5I/5tiDlHjUJMa9GAsvsNoQctZCGtzWF9S/v1LRh11fiHGd+r8aNRv8/olIGmgxWROPoUMbHtCW9AI+bjTjjBd+pqt3nnBAeTVKATLjETV14QYTj/jRfwzI4KprfwfCLWIG1XYnmDb8SlZorSJeGOXST1Bdozq17GBVwLXfiT/AFjQi8M1gmxjbknIgawKp5icmIuBSdZvYWOEJi2Ii7oXMu7dacEFEYXufUXAV3lJhu6AWWApyqQUaNmCAuMJwZRzo9hbceuO4V6xakpmzt2uVZzi+WisryTt3yiovvsOmqPUGNGL0frJe/hmI66qZYyF+jV9cY46BIuDuXnDUHrTLMBRXHAYYb76oISSgoDXJ0iPKgybEnCLvhOnFM29wRID31KgwldhdeCgGlGj1k6Mrcqw9pjcJhm6M/kzThaj2ZApjoCz2koOm0IpZr+/xcMoYrmBE9IOMXsxzGoeV2oGP1fYNqSybYXiQCyVlwAzPQ4UX9fRJV1NpAqv6VRKM2rLuCNN5do0rpIHsf4zET5Ar9f/Q3BPwvD4X4XjL1/NMrEgUHPAEIKzqAPHwb/heiXjEzByXYVaj1X//YWalA12VhUbfzl0Xf0aCvUs9E2IPNFgNuEAR6o1GSMrvi163wlQRcX+pcXdUbbffGWm46AcEU4GZMAWpZDOX5L0kLNYOWt+WsySc0iJ52wv+znKGAsDsMmuQP1dj6WProtez+nHcn+KkN/PyMB7mN2Aw6vzp2DuICUjsOBF/my888tA/IMe2ImuyfD6ExDMPWWYjE5h90KyCIPdtPFS6ihO2gyqt0cxQR43dH+BdH6Mx3L2sszvSKQBoKpQ8kwToiyykO6GiU3mt5O5po1hPQ7xlXwI3ARG/5A5uidABeef8sftRVw9ySnai45VdPkVHT3tQLuV5KVTq3At9YKFL7JVqB8CrZTB/AddAA6Hz+kAajUnq4BGKgau7sDOHV/x7/78lM0f6a2HOrU8mLJMv25cl8BbJkOzixIlxptXoVnzaUXClVQpR2Tl4bm5C84Q2pBs9EWQdqrmE6z9a8189gUUkME+yfLUlq8MqXkFoM6NIMGs5htoXfcG8vSarh6mrLfetAVtmbYv01EFCmV6FKe5wMh5SYdgy6OyiSF3A//TE+wy/qvcbCAKLazYokHZGzekZ+CK07BfH4Ge5Qq0O7+6t2ZbCBh1dmlpPSi3C3t+GXwn5Cr1UopRq7WSjng4hMCu/VSMTlyvSQjK4Nc2oNcgFQ4etRvURsPZc/bfz4E/Knaz2d4IXS+3xfCA999Ti+EL/uF0PxEPz0Qnh4IH/eB0JQS5WWqkm1XyB39/78AAAD//wMA

This isn't working, the primary bar disappears and the far left terriciary bar go blank aas well.
I also had to move the fan dance 3 and 4 down with the new upload of the Tilana fix to get all the icons to show.

**Comment by Asureon** [comment]
Hmm, sounds like something clashing with older/newer elements. Might be a dumb thing to ask but something easily overlooked, but is your DelvCD up to date?

**Comment by Spineshatter** [comment]
![dancer4](https://github.com/Asureon/UI_Collections/assets/167583265/5e71bdb5-1bbe-490e-bb53-237f1b8a684a)

Everything seems to be working atm, with the first En Avant you fixed for me as well as moving the fan dance 3 and 4 down.

Now for my next question....
Is Devilment meant to be on the left secondary field as well as the primary bar? Also did you know you had fan dance 2 on the teriary bar?

**Comment by Spineshatter** [comment]
> Hmm, sounds like something clashing with older/newer elements. Might be a dumb thing to ask but something easily overlooked, but is your DelvCD up to date?

It is

**Comment by Asureon** [comment]
> Now for my next question.... Is Devilment meant to be on the left secondary field as well as the primary bar? Also did you know you had fan dance 2 on the teriary bar?

Yes. The smaller Devilment is located for my keybind but I also wanted it into the primary bar because it's a major cd, and later on Starfall Dance will proc in its place at lvl 90.
Fan Dance 2 is just there as a placeholder for an empty keybind on my part, but also a visual marker that disappears when you're too low level when synced. Reason why is because it isn't on the primary bar.

**Comment by Spineshatter** [comment]
> > Now for my next question.... Is Devilment meant to be on the left secondary field as well as the primary bar? Also did you know you had fan dance 2 on the teriary bar?
> 
> Yes. The smaller Devilment is located for my keybind but I also wanted it into the primary bar because it's a major cd, and later on Starfall Dance will proc in its place at lvl 90. Fan Dance 2 is just there as a placeholder for an empty keybind on my part, but also a visual marker that disappears when you're too low level when synced. Reason why is because it isn't on the primary bar.

10-4, I've only made it 10 levels on my dancer so I'm learning as I go.

**Comment by Asureon** [comment]
> Everything seems to be working atm, with the first En Avant you fixed for me as well as moving the fan dance 3 and 4 down.

Is Fan Dance 3 visible on your primary bar too? It should be next to Fan dance.
Either way, I'll be closing the issue afterwards since neither I nor other users are reporting the bug so I suspect it's something from your side that's messing with it. But since you've found a fix for it, I won't look into it any further because I can't seem to find anything wrong from my side *shrug*

**Comment by Spineshatter** [comment]
It is only visible when it procs.... However I would like it to be greyed out like fan dance until its usable. I played with it some to see if I could get that result but im still learning.  It's greyed out in your example but mine is totally blank.
![DNC](https://github.com/Asureon/UI_Collections/assets/167583265/5aa4aff0-fd4d-4814-8352-2c44cfc7f63d)
![4222024](https://github.com/Asureon/UI_Collections/assets/167583265/8787af9b-8883-4f6c-90f0-1869e147cc4b)

**Comment by Asureon** [comment]
It should act the same way like Fan Dance. Check Fan Dance 3 visibility settings and the settings of the condition.

**Comment by Spineshatter** [comment]
I'm not having any luck with it at all.  I tried looking for other jobs with similar conditions most had extra variables like mana oom and job gauge. I'll just look more tomorrow.

**Comment by Asureon** [comment]
PLD's Divine Spirit should do the trick. It has the Divine Might buff merged into it. Just gotta change the skill names, set the main icon to desaturate and turn GCD tracker off. I think it's also in the exact same place where Fan Dance III is.

**Comment by Spineshatter** [comment]
Can't wait to get home and try it. I am having a ball using this setup. I'm really enjoying it. Thank you. Side note I haven't seen any bugs when I switch and use my other jobs yet.

**Comment by Spineshatter** [comment]
I don't understand. Fan Dance and Fan Dance IV work just fine.  Its when I change it to III that the icon disappears instead of desaturating.

I changed the lvl req. for Fan Dance IV to test it. And it works.  Just not for III.

I even changed Fan Dance IV to be Fan Dance III and the triggers and fourfold into threefold dance. with the same result. Icon dissapears. But I can change it back to Fan Dance IV and Fourfold Dance and it work just fine.

Maybe its something with the roman nurmerals. Wonder if there is a spell id.
